global:
  scrape_interval: 15s  # How often to gather metric data

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100', 'hu:9100', 'oak.taila6f38f.ts.net:9100', 'curo:9100', 'key:9100', 'gkc:9100', 'spirit:9100']  # Use container name
