global:
  scrape_interval: 15s  # How often to gather metric data

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100', 'hu:9100', 'oak:9100', 'curo:9100', 'key:9100', 'gkc:9100', 'spirit:9100', 'base:9100', 'ita:9100', 'sjm:9100', 'red:9100', 'tekton:9100']  # Use container name
